#ansible-playbook -i development 
---
- hosts: elastic
  remote_user: elastic
  gather_facts: true
  vars_files: 
   - "{{ev_var_path}}/group_vars/all.yml"
   - "{{ev_var_path}}/group_vars/elastic.yml"
    
  tasks:
   
   - include_role:
        name: ./roles/r_config_elasticsearchYML
...  
