#install_elasticsearch
---
- hosts: elastic
  remote_user: elastic
  gather_facts: true
  vars_files: 
   - "{{ev_var_path}}/group_vars/all.yml"
   - "{{ev_var_path}}/group_vars/elastic.yml"

  tasks:

    - name: create directory
      include_role: 
            name: ./roles/r_create_directory
      tags: create_directory    
    
    - name: include role install elasticsearch
      include_role: 
            name: ./roles/r_install_elasticsearch
      tags: install_elasticsearch      
            
           
    - name: include role config JVM option       
      include_role:
            name: ./roles/r_config_jvmOption
      tags: config_jvmOption      
            
            
    - name: include role config elasticsearchYML        
      include_role:
            name: ./roles/r_config_elasticsearchYML
      tags: 
        - config_elasticsearchYML
        
...  
