---
- hosts: elastic
  remote_user: elastic
  gather_facts: true
  vars_files: 
   - "{{ev_var_path}}/group_vars/all.yml"

  tasks:
   - name: Get running processes
     shell: "ps -ef | grep -v grep | grep -w 'elasticsearch-6.6.1' | awk '{print $2}' | head -n 1"
     register: running_processes

   - name: Kill running processes
     shell: "kill -9 {{ item }}"
     with_items: "{{ running_processes.stdout_lines }}"
   
   
       
   - name: remove home directory
     file: 
       path: "{{v_elastic_home}}"
       state: absent
       
   - name: remove software directory
     file: 
       path: "{{v_software_dir}}"
       state: absent 
  
#   - name: remove JDK directory
#     file: 
#       path: /apps/elk_marketing/jdk1.8.0_201
#       state: absent
       
   # - name: find data file to be deleted in Data directory
     # find:
       # paths: /data
       # patterns: "*_data"
       # file_type: directory
     # register: data_dir_to_delete

   # - name: delete data directory
     # file:
       # path: "{{ item.path }}"
       # state: absent
     # with_items: "{{ data_dir_to_delete.files }}"
     
- hosts: coordinating
  remote_user: elastic
  gather_facts: true
  vars:
    v_elastic_home: /apps/elk_marketing/coordinating
  tasks:
   - name: Get running processes
     shell: "ps -ef | grep -v grep | grep -w 'elasticsearch-6.6.1' | awk '{print $2}' | head -n 1"
     register: running_processes

   - name: Kill running processes
     shell: "kill -9 {{ item }}"
     with_items: "{{ running_processes.stdout_lines }}"
   
   
       

 
...
